### ISSUE TITLE
Notes: jump to content if title was set

### ISSUE THREAD

**Issue by JVariance** [holisticapps/Noteful-Issues#3]
I'm actually not sure if this is an issue or a feature request. However..

If you create a new note, the keyboard shows up so you can name the note directly. If you then press Enter/OK the keyboard hides.
I would expect the cursor to jump into the content section whith the keyboard still being opened.

**Comment by holisticapps** [comment]
Yes, that's a little inconvenient. I'll adjust that.

**Comment by holisticapps** [comment]
Corrected by 22 (1.25.3)
